interface CreatePROptions {
  runId: string;
  title: string;
  analysis: string;
  patch: string;
}

interface PRResult {
  prUrl: string;
  prNumber: number;
}

async function gh(path: string, init: RequestInit = {}): Promise<Response> {
  const token = process.env.GITHUB_TOKEN;
  if (!token) throw new Error("GITHUB_TOKEN not set");

  return fetch(`https://api.github.com${path}`, {
    ...init,
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28",
      ...(init.headers ?? {}),
    },
  });
}

export async function createFixPR(opts: CreatePROptions): Promise<PRResult | null> {
  const repo = process.env.GITHUB_REPO;
  const token = process.env.GITHUB_TOKEN;
  if (!repo || !token) return null;

  const [owner, name] = repo.split("/");
  if (!owner || !name) throw new Error("GITHUB_REPO must be owner/repo");

  const baseBranch = process.env.GITHUB_BASE_BRANCH ?? "main";
  const branch = `rift/fix/${opts.runId.slice(0, 20)}`;
  const fixPath = `.rift/fixes/${opts.runId}.md`;

  const repoRes = await gh(`/repos/${owner}/${name}`);
  if (!repoRes.ok) {
    throw new Error(`GitHub repo not found: ${repo}`);
  }
  const repoData = (await repoRes.json()) as { default_branch: string };
  const base = baseBranch || repoData.default_branch;

  const refRes = await gh(`/repos/${owner}/${name}/git/ref/heads/${base}`);
  if (!refRes.ok) throw new Error(`Base branch not found: ${base}`);
  const refData = (await refRes.json()) as { object: { sha: string } };
  const baseSha = refData.object.sha;

  const branchRes = await gh(`/repos/${owner}/${name}/git/refs`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ ref: `refs/heads/${branch}`, sha: baseSha }),
  });

  if (!branchRes.ok && branchRes.status !== 422) {
    const err = await branchRes.text();
    throw new Error(`Failed to create branch: ${err}`);
  }

  const fileContent = [
    `# Rift auto-fix for ${opts.runId}`,
    "",
    opts.analysis,
    "",
    "## Patch",
    "",
    "```diff",
    opts.patch,
    "```",
  ].join("\n");

  const contentRes = await gh(`/repos/${owner}/${name}/contents/${fixPath}`, {
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      message: opts.title,
      content: Buffer.from(fileContent).toString("base64"),
      branch,
    }),
  });

  if (!contentRes.ok) {
    const err = await contentRes.text();
    throw new Error(`Failed to commit fix file: ${err}`);
  }

  const prBody = [
    "## Rift Auto-Remediation (Hermes)",
    "",
    `**Run:** \`${opts.runId}\``,
    "",
    opts.analysis,
    "",
    "### Suggested patch",
    "",
    "```diff",
    opts.patch,
    "```",
    "",
    "---",
    "*Generated by [Rift](https://github.com) + Nous Hermes Agent. Review before merging.*",
  ].join("\n");

  const prRes = await gh(`/repos/${owner}/${name}/pulls`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      title: opts.title,
      head: branch,
      base: base,
      body: prBody,
    }),
  });

  if (!prRes.ok) {
    const err = await prRes.text();
    throw new Error(`Failed to open PR: ${err}`);
  }

  const pr = (await prRes.json()) as { html_url: string; number: number };
  return { prUrl: pr.html_url, prNumber: pr.number };
}
